// IT SI MODULE JAVASCRIPT WHICH IS MANDATORY TO BE DEFINED IN JAVASCRIPT IN HTML FILE HERE SCRIPT IS DEFINED ---> 
// AS MJS --> THAT IS MODULE JS -->HERE FUNCTION SHOULD BE EXPORTED FROM HERE AND CONSOLE IS IMPORTED IN CONSOLE
//  FILE


// THIS NORMAL EXPORT IS KNOWN AS NAMED EXPORT
 export const add =(a,b)=>{
    return a+b;
}

export const mul =(a,b)=>{
    return a*b;
}


// DEFINING DEFAULT EXPORT AS IT SI ONLY DEFINED TO ONE VARIBALE AND IT ACNNOT BE IMPORTED WITHIN SAME CURLY 
// BRACES USING COMMAS IT IS IMPPORTED OUTSIDE IT
//  THIS IS KNOWN AS DEFAULT EXPORT

const divide = (a,b)=>{
    return a/b;
}
// EXPORT DEFAULT SHOULD BE DEFINED SEPERATELY AS FIRST ONLY VARIABLE SHOULD BE DECLARED AS FOLLOWS:
export default divide;

